### ISSUE TITLE
read ply file back with features

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/eEcoLiDAR#98]
I tried to read back an ply file for further analysis. I got an error message (see bellow). 

Code:

from laserchicken import read_ply

pc_wfea = read_ply.read('C:/zsofia/Amsterdam/Geobia/Result/06en2_merged_kiv3._ground_height_kiv_kiv._cylinder2.5.ply')

Error:

Traceback (most recent call last):
  File "exploration.py", line 24, in <module>
    pc_wfea = read_ply.read('C:/zsofia/Amsterdam/Geobia/Result/06en2_merged_kiv3._ground_height_kiv_kiv._cylinder2.5.ply')
  File "C:/zsofia/Amsterdam/GitHub/eEcoLiDAR/eEcoLiDAR\laserchicken\read_ply.py", line 19, in read
    index = read_header(ply)
  File "C:/zsofia/Amsterdam/GitHub/eEcoLiDAR/eEcoLiDAR\laserchicken\read_ply.py", line 64, in read_header
    comments[i] = ast.literal_eval(comment_line)
  File "C:\Users\zsofi\Anaconda3\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Users\zsofi\Anaconda3\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    [
    ^
SyntaxError: unexpected EOF while parsing

**Comment by cwmeijer** [comment]
I need some more information. Could you send me the data file with a small script that will trigger the error?

**Comment by komazsofi** [comment]
Example code: 

"""
import sys
import argparse

import numpy as np
import pandas as pd
import geopandas as gpd

import matplotlib.pyplot as plt
import seaborn as sns

#parser = argparse.ArgumentParser()
#parser.add_argument('path', help='where the files are located')
#parser.add_argument('training', help='polygon shape file with class')
#parser.add_argument('features', help='point cloud with features')
#args = parser.parse_args()

#pc_wfea = pd.read_csv(args.path+args.features,sep=';')
#print(pc_wfea.dtypes)

# Reduction into 2D and visualize

import sys
sys.path.insert(0, 'D:/GitHub/eEcoLiDAR/develop-branch/eEcoLiDAR/')

from laserchicken import read_ply

pc_wfea = read_ply.read('D:/Results/Geobia/Work/02gz2_merged_kiv1_kivtest._ground_height._cylinder2.5.ply')
"""

You can find the ply file at dcache (I sent you a link where).

Error message:

Traceback (most recent call last):
  File "regiongrowing.py", line 37, in <module>
    pc_wfea = read_ply.read('D:/Results/Geobia/Work/02gz2_merged_kiv1_kivtest._ground_height._cylinder2.5.ply')
  File "D:/GitHub/eEcoLiDAR/develop-branch/eEcoLiDAR\laserchicken\read_ply.py", line 19, in read
    index = read_header(ply)
  File "D:/GitHub/eEcoLiDAR/develop-branch/eEcoLiDAR\laserchicken\read_ply.py", line 64, in read_header
    comments[i] = ast.literal_eval(comment_line)
  File "C:\Program Files\Miniconda3\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Program Files\Miniconda3\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    [
    ^
SyntaxError: unexpected EOF while parsing

**Comment by cwmeijer** [comment]
I changed the reading and writing logs in the ply files. This means that the problem should now be solved. However, ply files created before this change can still not be read. This problem is only fixed for new files.
